# Keyd remap COPILOT -> CTRL_R, SHIFT_L + SHIFT_R -> CAPSLOCK
# and CAPSLOCK -> BACKSPACE

# Place in /etc/keyd/default.conf

# Edit the file to your liking

[ids]
*

[main]
leftshift+leftmeta+f23 = layer(control)
capslock = backspace

# Shift + capslock for capslock
[shift]
capslock = capslock